USE [master]
GO

/****** Object:  Database [ExamenPM01]    Script Date: 05.07.2022 11:35:33 ******/
CREATE DATABASE [ExamenPM01]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExamenPM01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ExamenPM01.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExamenPM01_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ExamenPM01_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExamenPM01].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExamenPM01] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExamenPM01] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExamenPM01] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExamenPM01] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExamenPM01] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExamenPM01] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ExamenPM01] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExamenPM01] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExamenPM01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExamenPM01] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExamenPM01] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExamenPM01] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExamenPM01] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ExamenPM01] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExamenPM01] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ExamenPM01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExamenPM01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExamenPM01] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExamenPM01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExamenPM01] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExamenPM01] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExamenPM01] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExamenPM01] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ExamenPM01] SET  MULTI_USER 
GO

ALTER DATABASE [ExamenPM01] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExamenPM01] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExamenPM01] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ExamenPM01] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ExamenPM01] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ExamenPM01] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ExamenPM01] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ExamenPM01] SET  READ_WRITE 
GO

